version: "3"

services:
  server:
    image: webchat:server
    build: ./server
    container_name: server
    hostname: server
    ports:
      - 8080:8080

  client:
    image: webchat:client
    build: ./client
    container_name: client
    hostname: client
    ports:
      - 80:80

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
